#!/bin/bash

if [ $# -ne 1 ]; then
  echo "need exactly 1 param target dir"
  exit 1
fi

TARGET_DIR=$1

# Check if the directory exists
if [ ! -d "$TARGET_DIR" ]; then
    echo "Directory does not exist: $TARGET_DIR"
    exit 1
fi

# Change to the ~/bin directory
cd "$TARGET_DIR" || exit 1

# Check if the directory is a Git repository
if [ ! -d .git ]; then
    echo "Not a Git repository: $TARGET_DIR"
    exit 1
fi

# Fetch the latest changes from the remote repository
echo "fetching $TARGET_DIR"
git fetch origin

# Check if there are any changes to pull
if git diff --quiet HEAD -- origin/main; then
    echo "The $TARGET_DIR directory is up to date."
else
    echo "The $TARGET_DIR directory has updates available. You should run 'git pull' to update it."
fi

