#! /bin/bash
#
# Define the dotfiles directory and GitHub repository
DOTFILES_DIR=$HOME/dotfiles
GITHUB_REPO="git@github.com:LiuTaowen-Tony/dotfiles.git"

# Check if the dotfiles directory exists
if [ ! -d "$DOTFILES_DIR" ]; then
    echo "Directory ~/dotfiles does not exist. Cloning from GitHub..."
    # Clone the GitHub repository
    git clone $GITHUB_REPO $DOTFILES_DIR
else
    echo "Directory ~/dotfiles already exists."
fi

cp -r $HOME/.SpaceVim.d $DOTFILES_DIR
cp $HOME/.zshrc $DOTFILES_DIR

cd $HOME/dotfiles

git add .
git commit -m "update dotfiles"
git push

if [ $? -ne 0 ]; then
   echo "push failed need to resolve conflicts"
fi

