#! /bin/bash

name="$(pname .venv)"
echo "${name}"

if [ -z "${VENV_DIR}" ]; then
  VENV_DIR="${HOME}/venvs"
fi

actual_venv_dir="${VENV_DIR}/${name}"
echo "$actual_venv_dir"

python3 -m venv "$actual_venv_dir"
ln -s "$acutal_venv_dir" .venv

if [ ! -d ".git" ]; then
  echo "init git"
  git init
  init_gitignore
fi

